//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PavilionsBase : DbContext
    {
        private static PavilionsBase context_;

        public PavilionsBase()
            : base("name=PavilionsBase")
        {
        }

        public static PavilionsBase GetContext()
        {
            if (context_ == null)
                context_ = new PavilionsBase();
            return context_;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<ImagesShoppingMalls> ImagesShoppingMalls { get; set; }
        public virtual DbSet<Pavilions> Pavilions { get; set; }
        public virtual DbSet<PhotoEmployee> PhotoEmployee { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ShoppingMalls> ShoppingMalls { get; set; }
        public virtual DbSet<StatePavilions> StatePavilions { get; set; }
        public virtual DbSet<StatusEmployee> StatusEmployee { get; set; }
        public virtual DbSet<StatusPavilions> StatusPavilions { get; set; }
        public virtual DbSet<StatusRent> StatusRent { get; set; }
        public virtual DbSet<StatusShoppingMalls> StatusShoppingMalls { get; set; }
        public virtual DbSet<Tenants> Tenants { get; set; }
    }
}
