//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PavilionsBase : DbContext
    {
        private static PavilionsBase context_;

        public PavilionsBase()
            : base("name=PavilionsBase")
        {
        }

        public static PavilionsBase GetContext()
        {
            if (context_ == null)
                context_ = new PavilionsBase();
            return context_;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Mall> Malls { get; set; }
        public virtual DbSet<Pavilion> Pavilions { get; set; }
        public virtual DbSet<Rent> Rents { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatePavilion> StatePavilions { get; set; }
        public virtual DbSet<StatusEmployee> StatusEmployees { get; set; }
        public virtual DbSet<StatusMall> StatusMalls { get; set; }
        public virtual DbSet<StatusPavilion> StatusPavilions { get; set; }
        public virtual DbSet<StatusRent> StatusRents { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
    }
}
