//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public int IdPavilion { get; set; }
        public string Name { get; set; }
        public int IdShoppingMall { get; set; }
        public int Floor { get; set; }
        public int IdStatusPavilion { get; set; }
        public float Square { get; set; }
        public float CostPerMeter { get; set; }
        public float ValueAddedFactor { get; set; }
    
        public virtual ShoppingMalls ShoppingMalls { get; set; }
        public virtual StatusPavilions StatusPavilions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
        public virtual StatePavilions StatePavilions { get; set; }
    }
}
