//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilion()
        {
            this.StatePavilions = new HashSet<StatePavilion>();
        }
    
        public int IdPavilion { get; set; }
        public Nullable<int> IdShoppingMall { get; set; }
        public string NamePavilions { get; set; }
        public Nullable<int> FloorPavilion { get; set; }
        public Nullable<int> IdStatusPavilion { get; set; }
        public Nullable<double> SquarePavilions { get; set; }
        public Nullable<double> CostPerMeter { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
        public Nullable<int> IdRent { get; set; }
    
        public virtual Mall Mall { get; set; }
        public virtual StatusPavilion StatusPavilion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatePavilion> StatePavilions { get; set; }
    }
}
