//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        public int IdPavilion { get; set; }
        public Nullable<int> IdShoppingMall { get; set; }
        public string NamePavilions { get; set; }
        public Nullable<int> FloorPavilion { get; set; }
        public Nullable<int> IdStatusPavilion { get; set; }
        public Nullable<double> SquarePavilions { get; set; }
        public Nullable<double> CostPerMeter { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
        public Nullable<int> IdRent { get; set; }
    
        public virtual Rent Rent { get; set; }
        public virtual ShoppingMalls ShoppingMalls { get; set; }
        public virtual StatusPavilions StatusPavilions { get; set; }
        public virtual StatePavilions StatePavilions { get; set; }
    }
}
