//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.Pavilions = new HashSet<Pavilions>();
        }
    
        public int IdRent { get; set; }
        public Nullable<int> IdTenant { get; set; }
        public Nullable<int> IdPavilion { get; set; }
        public Nullable<int> IdStatusRent { get; set; }
        public Nullable<System.DateTime> StartOfLease { get; set; }
        public Nullable<System.DateTime> EndOfLease { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilions> Pavilions { get; set; }
        public virtual StatusRent StatusRent { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
