//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int IdRent { get; set; }
        public int IdTenant { get; set; }
        public int IdPavilion { get; set; }
        public int IdStatusRent { get; set; }
        public System.DateTime StartOfLease { get; set; }
        public System.DateTime EndOfLease { get; set; }
    
        public virtual Pavilions Pavilions { get; set; }
        public virtual StatusRent StatusRent { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
