//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticePavilions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingMalls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingMalls()
        {
            this.Pavilions = new HashSet<Pavilions>();
        }
    
        public int IdShoppingMall { get; set; }
        public string NameShoppingMalls { get; set; }
        public Nullable<int> IdStatusShoppingMalls { get; set; }
        public Nullable<int> IdCity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
        public Nullable<int> NumberOfStoreys { get; set; }
        public Nullable<int> IdImageShoppingMall { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ImagesShoppingMalls ImagesShoppingMalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilions> Pavilions { get; set; }
        public virtual StatusShoppingMalls StatusShoppingMalls { get; set; }
    }
}
